#!/usr/bin/env python3
"""WanderQuest sprite generator — 16-bit pixel art in 3 theme palettes.

Roles: . transparent | O outline | A primary | B secondary | C accent
       W white/highlight | S shadow/dark | G glow
"""
import os, colorsys
from PIL import Image, ImageDraw

OUT = "/sessions/wonderful-wizardly-knuth/mnt/Projects/new-x3-app/app/src/main/assets/sprites"
RES = "/sessions/wonderful-wizardly-knuth/mnt/Projects/new-x3-app/app/src/main/res"

# ---------------- pixel maps (16x16 unless noted) ----------------
SPRITES = {
"gem": """
................
................
....OOOOOOOO....
...OWWABBBAO....
..OWWAABBBAAO...
..OWAAABBAAAO...
..OAAAABBAAAO...
...OAAABBAAO....
...OSAABBASO....
....OSABBSO.....
....OSABBSO.....
.....OSBSO......
.....OSBSO......
......OSO.......
.......O........
................
""",
"potion": """
................
......OOO.......
......OBO.......
......OBO.......
.....OOAOO......
.....OWAAO......
....OWAAAAO.....
...OWAACAAAO....
...OAACCCAAO....
...OAACCCAAO....
...OACCCCCAO....
...OSACCCASO....
....OSACASO.....
.....OOOOO......
................
................
""",
"scroll": """
................
................
...OOOOOOOOOO...
..OWAAAAAAAAWO..
..OAOOOOOOOOAO..
..OAOBBBBBBOAO..
..OAOOOOOOOOAO..
..OAOBBBBOOOAO..
..OAOOOOOOOOAO..
..OAOBBBBBBOAO..
..OAOOOOOOOOAO..
..OWAAAAAAAAWO..
...OOOOOOOOOO...
................
................
................
""",
"key": """
................
................
....OOOO........
...OAAAAO.......
..OAWOOAAO......
..OAO..OAO......
..OAO..OAO......
..OAWOOAAO......
...OAAAAO.......
....OOAO........
......OAO.......
......OAOO......
......OAAAO.....
......OAOO......
......OOO.......
................
""",
"crown": """
................
................
................
...O........O...
..OAO..OO..OAO..
..OAO.OAAO.OAO..
..OAAOAWAAOAAO..
..OAAAAAAAAAAO..
..OAAAAAAAAAAO..
..OABCBABCBAAO..
..OAAAAAAAAAAO..
..OSSSSSSSSSSO..
...OOOOOOOOOO...
................
................
................
""",
"shroom": """
................
................
.....OOOOO......
....OAAAAAO.....
...OAWAABAAO....
..OAABAAAAWAO...
..OAAAAWAAAAO...
..OABAAAAABAO...
..OOOOOOOOOOO...
....OWBBBWO.....
....OBBBBBO.....
....OBBWBBO.....
....OSBBBSO.....
.....OOOOO......
................
................
""",
"ring": """
................
................
................
......OOO.......
.....OCWCO......
.....OCCCO......
....O.OOO.O.....
...OAO...OAO....
..OAO.....OAO...
..OAO.....OAO...
..OAO.....OAO...
...OAO...OAO....
....OAAOAAO.....
......OOO.......
................
................
""",
"chest": """
................
................
...OOOOOOOOOO...
..OAAAAAAAAAAO..
..OAWAAAAAAWAO..
..OOOOOOOOOOOO..
..OBBBBOCOBBBO..
..OBBBBOCOBBBO..
..OBBBOOOOOBBO..
..OBBBOCCCOBBO..
..OBBBBOOOBBBO..
..OBBBBBBBBBBO..
..OSSSSSSSSSSO..
...OOOOOOOOOO...
................
................
""",
"shrine": """
................
.......OO.......
......OGGO......
.....OGWWGO.....
.....OGGGGO.....
....OOOOOOOO....
....OAAAAAAO....
.....OAAAAO.....
.....OABBAO.....
.....OABBAO.....
.....OABBAO.....
....OAABBAAO....
...OAAAAAAAAO...
..OSSSSSSSSSSO..
..OOOOOOOOOOOO..
................
""",
"sign": """
................
...OOOOOOOOOO...
..OAAAAAAAAAAO..
..OAWWBWWBWWAO..
..OABBBBBBBBAO..
..OAWBWWBWWBAO..
..OABBBBBBBBAO..
..OAWWBWWBWWAO..
...OOOOBBOOOO...
......OBBO......
......OBBO......
......OBBO......
......OBBO......
.....OSBBSO.....
....OSSSSSSO....
................
""",
"well": """
................
................
....OOOOOOOO....
...OAAAAAAAAO...
...OASSSSSAAO...
...OAOOOOOAO....
...OACCCCCAO....
...OACWWWCAO....
...OACWBWCAO....
...OACWWWCAO....
...OACCCCCAO....
..OAAAAAAAAAO...
..OBBBBBBBBBBO..
..OSSSSSSSSSSO..
..OOOOOOOOOOO...
................
""",
"portal": """
................
.....OOOOOO.....
...OOAAAAAAOO...
..OAACCCCCCAAO..
.OAACWWAAWWCAAO.
.OACWAACCAAWCAO.
OAACWACCCCAWCAAO
OACWACCWWCCAWCAO
OACWACCWWCCAWCAO
OAACWACCCCAWCAAO
.OACWAACCAAWCAO.
.OAACWWAAWWCAAO.
..OAACCCCCCAAO..
...OOAAAAAAOO...
.....OOOOOO.....
................
""",
"slime": """
................
................
................
................
......OOOO......
....OOAAAAOO....
...OAAAAAAAAO...
..OAAWAAAAWAAO..
..OAWSAAAASWAO..
.OAAAAAAAAAAAAO.
.OAAAASSSSAAAAO.
.OAAAAAAAAAAAAO.
..OAAAAAAAAAAO..
...OOOOOOOOOO...
................
................
""",
"goblin": """
................
...O........O...
...OO......OO...
...OAOOOOOOAO...
....OAAAAAAO....
...OAAAAAAAAO...
...OASWAAWSAO...
...OAAAAAAAAO...
...OAASSSSAAO...
....OAAAAAAO....
...OBOAAAAOBO...
..OBBOAAAAOBBO..
..OBOOAAAAOOBO..
.....OAOOAO.....
.....OO..OO.....
................
""",
"imp": """
................
..O..........O..
..OO........OO..
...OO..OO..OO...
...OAOOAAOOAO...
....OAAAAAAO....
...OAWAAAAWAO...
...OAACAACAAO...
...OAAAAAAAAO...
....OASSSSAO....
.....OAAAAO.....
....OAAAAAAO....
...OAO.OO.OAO...
...O...OO...O...
.......OO.O.....
........OO......
""",
"skeleton": """
................
.....OOOOO......
....OAAAAAO.....
...OAAAAAAAO....
...OASAAASAO....
...OASAAASAO....
...OAAAAAAAO....
....OASSSAO.....
.....OOOOO......
....OAOAOAO.....
...OAOAAAOAO....
...OAOAAAOAO....
....O.OAO.O.....
......OAO.......
.....OA.AO......
.....O...O......
""",
"mimic": """
................
................
...OOOOOOOOOO...
..OAAAAAAAAAAO..
..OAWAAAAAAWAO..
..OOOOOOOOOOOO..
..OWSWSWSWSWSO..
..OSWSWSWSWSWO..
..OBBBOOOOBBBO..
..OBBOCWCOBBBO..
..OBBBOCOBBBBO..
..OBBBBBBBBBBO..
..OSSSSSSSSSSO..
...OOOOOOOOOO...
................
................
""",
"sunpetal": """
................
................
......OO........
.....OAAO.OO....
..OO.OAAOOAAO...
.OAAOOAAOAAO....
..OAAOACOAO.....
...OACCCCAO.....
..OAOACCAOAO....
.OAAOOAAOOAAO...
..OO.OAAO.OO....
......OBO.......
......OBO.......
.....OBO........
......OBO.......
................
""",
"moonleaf": """
................
................
..........OO....
........OOAAO...
......OOAAAAO...
....OOAAAWAAO...
...OAAAAWAAAO...
..OAAAWAAAAO....
..OAAWAAAAO.....
..OAWAAAAO......
..OAAAAOO.......
...OAAO.........
....OBO.........
...OBO..........
..OBO...........
................
""",
"glowcap": """
................
................
................
.....OOOOO......
....OACACAO.....
...OACACACAO....
..OACACACACAO...
..OAAAAAAAAAO...
..OOOOOOOOOOO...
.....OWBWO......
.....OBWBO......
.....OWBWO......
.....OBBBO......
......OOO.......
................
................
""",
"dewroot": """
................
................
.....OO.OO......
....OAAOAAO.....
....OAAAAO......
.....OAAO.......
.....OAAO.......
....OOAAOO......
...OBABABBO.....
...OBBABBBO.....
....OBABBO......
....OBABO.......
.....OBBO.......
.....OBO........
......O.........
................
""",
"starbloom": """
................
.......O........
......OWO.......
......OWO.......
..OO.OAWAO.OO...
...OWOAAAOWO....
....OAACAAO.....
..OWWACCCAWWO...
....OAACAAO.....
...OWOAAAOWO....
..OO.OAWAO.OO...
......OWO.......
......OWO.......
.......O........
......OBO.......
.....OBO........
""",
"wand": """
................
............OO..
...........OWAO.
..........OAWAO.
.......O..OAAO..
......OBO..OO...
.......OBO......
......OBBBO.....
.....OBOBO......
....OBO.O.......
...OBO..........
..OBO...........
.OBO............
.OO.............
................
................
""",
"rod": """
................
......OOO.......
.....OCWCO......
....OCCCCCO.....
....OCWCCCO.....
.....OCCCO......
......OOO.......
.....OBABO......
......OAO.......
......OAO.......
......OAO.......
......OAO.......
......OAO.......
.....OBABO......
......OOO.......
................
""",
"staff": """
................
.......OO.......
......OWAO......
.....OWAAAO.....
.....OAACAO.....
......OAAO......
....O..OO..O....
.....O.OO.O.....
......OBBO......
......OBBO......
......OBBO......
......OBBO......
......OBBO......
......OBBO......
.....OOOOOO.....
................
""",
"armor": """
................
................
..OOO......OOO..
.OAAAO....OAAAO.
.OAAAOOOOOOAAAO.
.OAOAAAAAAAAOAO.
.OAOAAWAAAAAOAO.
..O.OAAAAAAO.O..
....OAACAAAO....
....OAACCAAO....
....OAAAAAAO....
....OBAAAABO....
.....OBAABO.....
.....OBBBBO.....
......OOOO......
................
""",
"boots": """
................
................
................
...OO....OO.....
...OAO...OAO....
...OAO...OAO....
...OAO...OAO....
...OAO...OAO....
...OABO..OABO...
...OAABO.OAABO..
...OAAABOOAAABO.
...OSAAAOOSAAAO.
....OSSSO.OSSSO.
.....OOO...OOO..
................
................
""",
"heart": """
................
................
..OOO....OOO....
.OAAAO..OAAAO...
OAWAAAOOAAAAAO..
OAWAAAAAAAAAAAO.
OAAAAAAAAAAAAAO.
OAAAAAAAAAAAAAO.
.OAAAAAAAAAAAO..
..OAAAAAAAAAO...
...OAAAAAAAO....
....OAAAAAO.....
.....OAAAO......
......OAO.......
.......O........
................
""",
"ghost": """
................
.....OOOOO......
....OAAAAAO.....
...OAAAAAAAO....
..OAAAAAAAAAO...
..OASAAAASAAO...
..OAWSAAAWSAO...
..OAAAAAAAAAO...
..OAAAOOOAAAO...
..OAAAAAAAAAO...
..OAAAAAAAAAO...
..OAAAAAAAAAO...
..OAOAAOAAOAO...
..OO.OAO.OO.O...
......O.........
................
""",
"npc": """
................
.....OOOOO......
....OBBBBBO.....
...OBBBBBBBO....
...OBOAAAOBO....
...OBAWAWABO....
...OBAAAAABO....
....OAASAAO.....
...OBBAAABBO....
..OBOBBBBBOBO...
..OBO.OCO.OBO...
..OBOOCWCOOBO...
..OBBOOCOOBBO...
...OBBBBBBBO....
....OOOOOOO.....
................
""",
"beacon": """
................
.......OO.......
......OGGO......
.....OGWWGO.....
.....OGGGGO.....
....OOOOOOO.....
.....OAAAO......
.....OABAO......
.....OAABO......
....OABAAO......
....OAABAO......
...OABAABAO.....
...OAABAAAO.....
..OAAAAABAAO....
..OOOOOOOOOO....
................
""",
"lever": """
................
................
................
..........OO....
.........OAAO...
........OAAO....
.......OAO......
......OAO.......
.....OAO........
....OAO.........
...OOOOOO.......
..OBBBBBBO......
..OBBWBBBO......
..OSSSSSSO......
..OOOOOOOO......
................
""",
"pool": """
................
................
................
................
....OOOOOOOO....
..OOAAAAAAAAOO..
.OAAWAAAAAAAAO..
OAAAAAAWAAAAAAO.
OAAWAAAAAAAWAAO.
.OAAAAAWAAAAAO..
..OOAAAAAAAOO...
....OOOOOOO.....
................
................
................
................
""",
"satchel": """
................
................
......OOO.......
.....OBABO......
.....OB.BO......
....OOOOOOO.....
...OAAAAAAAO....
..OAAWAAAAAAO...
..OAAAAAAAAAO...
..OABBBBBBBAO...
..OAAOOOOOAAO...
..OAAACCAAAAO...
..OSAAAAAAASO...
...OSSAAASSO....
....OOOOOOO.....
................
""",
"ghoul": """
................
.....OOOOO......
....OAAAAAO.....
...OAAAAAAAO....
..OAASAAASAAO...
..OAWSAAAWSAO...
..OAAAAAAAAAO...
..OAAASSSAAAO...
..OAAAAAAAAAO...
.OAAOAAAAAOAAO..
.OAOOAAAAAOOAO..
.OAO.OAAAO.OAO..
.OO..OAAAO..OO..
......OAO.......
.....O.O.O......
................
""",
"bat": """
................
................
..O..........O..
..OO........OO..
..OAO......OAO..
..OAAO.OO.OAAO..
..OAAAOAAOAAAO..
..OAAAAAAAAAAO..
...OAAWCWAAAO...
....OAACAAAO....
.....OAAAOO.....
.....OSASO......
....O.OSO.O.....
.......O........
................
................
""",
"wolf": """
................
..O.........O...
..OO.......OO...
..OAO.....OAO...
..OAAOOOOOAAO...
..OAAAAAAAAAO...
..OASWAAWSAAO...
..OAAAAAAAAAO...
...OAASSAAO.....
...OAAASAAO.....
....OAASAAO.....
....OASSSAO.....
.....OAAAO......
......OWO.......
.......O........
................
""",
}

# 32x32 scare faces
SCARES = {
"scare_ghoul": """
................................
......OOOOOOOOOOOOOOOOOOO......
....OOAAAAAAAAAAAAAAAAAAAOO....
...OAAAAAAAAAAAAAAAAAAAAAAAO...
..OAAAAAAAAAAAAAAAAAAAAAAAAAO..
..OAAASSSSSAAAAAAAASSSSSAAAAO..
.OAAASSSSSSSAAAAAASSSSSSSAAAAO.
.OAAASWWSSSSAAAAAASSSSWWSAAAAO.
.OAAASWWSSSSAAAAAASSSSWWSAAAAO.
.OAAASSSSSSSAAAAAASSSSSSSAAAAO.
.OAAAASSSSSAAAAAAAASSSSSAAAAAO.
.OAAAAAAAAAAAAAAAAAAAAAAAAAAAO.
.OAAAAAAAAASSAASSAAAAAAAAAAAAO.
.OAAAAAAAAASSAASSAAAAAAAAAAAAO.
.OAAAAAAAAAAAAAAAAAAAAAAAAAAAO.
.OAAAASSSSSSSSSSSSSSSSSSAAAAAO.
.OAAASSSSSSSSSSSSSSSSSSSSAAAAO.
.OAAASSWWSSWWSSWWSSWWSSWSAAAAO.
.OAAASSWWSSWWSSWWSSWWSSWSAAAAO.
.OAAASSSSSSSSSSSSSSSSSSSSAAAAO.
.OAAAASSSSSSSSSSSSSSSSSSAAAAAO.
..OAAAAASSSSSSSSSSSSSSAAAAAAO..
..OAAAAAAAAAAAAAAAAAAAAAAAAAO..
...OAAAAAAAAAAAAAAAAAAAAAAAO...
....OOAAAAAAAAAAAAAAAAAAAOO....
......OOOOOOOOOOOOOOOOOOO......
................................
................................
................................
................................
................................
................................
................................
""",
"scare_bat": """
................................
....O......................O....
....OO....................OO....
....OAO..................OAO....
....OAAO................OAAO....
....OAAAO..............OAAAO....
....OAAAAOOOOOOOOOOOOOOAAAAO....
....OAAAAAAAAAAAAAAAAAAAAAAO....
...OAAAAAAAAAAAAAAAAAAAAAAAAO...
..OAAAAAAAAAAAAAAAAAAAAAAAAAAO..
..OAAAWWCCWWAAAAAAAAWWCCWWAAAO..
..OAAWWCCCCWWAAAAAAWWCCCCWWAAO..
..OAAWCCSSCCWAAAAAAWCCSSCCWAAO..
..OAAWCCSSCCWAAAAAAWCCSSCCWAAO..
..OAAWWCCCCWWAAAAAAWWCCCCWWAAO..
..OAAAWWCCWWAAAAAAAAWWCCWWAAAO..
..OAAAAAAAAAAAAAAAAAAAAAAAAAAO..
..OAAAAAAAASSSSSSSSSSAAAAAAAAO..
...OAAAAASSSSSSSSSSSSSSAAAAAO...
...OAAAASSWWSSWWSSWWSSWSAAAAO...
....OAAASWWSSWWSSWWSSWWSAAAO....
....OAAASSSSSSSSSSSSSSSSAAAO....
.....OAAAASSSSSSSSSSSSAAAAO.....
......OAAAAAAAAAAAAAAAAAAO......
.......OOOOOOOOOOOOOOOOOO.......
................................
................................
................................
................................
................................
................................
................................
""",
"scare_wolf": """
................................
..O..........................O..
..OO........................OO..
..OAO......................OAO..
..OAAO....................OAAO..
..OAAAOOOOOOOOOOOOOOOOOOOOAAAO..
..OAAAAAAAAAAAAAAAAAAAAAAAAAAO..
..OAAAAAAAAAAAAAAAAAAAAAAAAAAO..
..OAASSWWSSAAAAAAAAAASSWWSSAAO..
..OAASWWWWSSAAAAAAAASSWWWWSAAO..
..OAASWWCCSSAAAAAAAASSCCWWSAAO..
..OAASSCCSSAAAAAAAAAASSCCSSAAO..
..OAAASSSSAAAAAAAAAAAASSSSAAAO..
..OAAAAAAAAAAASSSSAAAAAAAAAAAO..
..OAAAAAAAAAASSSSSSAAAAAAAAAAO..
...OAAAAAAAAASSSSSSAAAAAAAAAO...
...OAAAAAAAAAASSSSAAAAAAAAAO....
....OAAASSSSSSSSSSSSSSSAAAAO....
....OAASSSSSSSSSSSSSSSSSAAO.....
.....OASWWSSSWWSSSWWSSWWSAO.....
.....OASWWSSSWWSSSWWSSWWSAO.....
......OASSSSSSSSSSSSSSSSAO......
......OAASSSSSSSSSSSSSSAAO......
.......OAAAASSSSSSSSAAAAO.......
........OAAAAAAAAAAAAAAO........
.........OOOOOOOOOOOOOO.........
................................
................................
................................
................................
................................
................................
""",
}

# Base (fantasy) palettes per sprite: role -> RGB
BASE = {
"gem":    {"A": (60, 200, 255), "B": (30, 120, 230), "C": (200, 240, 255)},
"potion": {"A": (90, 220, 120), "B": (160, 110, 60), "C": (40, 170, 80)},
"scroll": {"A": (235, 215, 160), "B": (140, 100, 60), "C": (200, 170, 110)},
"key":    {"A": (250, 200, 60), "B": (200, 150, 40), "C": (255, 230, 120)},
"crown":  {"A": (255, 210, 60), "B": (230, 60, 80), "C": (60, 110, 255)},
"shroom": {"A": (235, 70, 70), "B": (245, 230, 200), "C": (255, 150, 150)},
"ring":   {"A": (220, 220, 235), "B": (180, 180, 200), "C": (255, 80, 180)},
"chest":  {"A": (170, 110, 50), "B": (130, 80, 40), "C": (255, 210, 80)},
"satchel": {"A": (150, 100, 55), "B": (110, 70, 40), "C": (255, 210, 80)},
"wand":   {"A": (255, 230, 120), "B": (140, 90, 50), "C": (255, 255, 200)},
"slime":  {"A": (110, 220, 130), "B": (70, 170, 90), "C": (180, 255, 190)},
"portal": {"A": (120, 80, 200), "B": (80, 50, 140), "C": (190, 140, 255)},
"sign":   {"A": (160, 110, 60), "B": (110, 75, 45), "C": (255, 230, 150)},
"well":   {"A": (150, 150, 165), "B": (110, 110, 125), "C": (90, 170, 220)},
"goblin": {"A": (140, 180, 90), "B": (110, 80, 50), "C": (255, 220, 90)},
"imp":    {"A": (220, 100, 80), "B": (160, 60, 50), "C": (255, 220, 90)},
"skeleton": {"A": (230, 228, 210), "B": (180, 175, 155), "C": (90, 200, 120)},
"mimic":  {"A": (170, 110, 50), "B": (130, 80, 40), "C": (255, 80, 80)},
"sunpetal": {"A": (255, 200, 80), "B": (90, 140, 60), "C": (255, 240, 150)},
"moonleaf": {"A": (130, 200, 160), "B": (80, 120, 90), "C": (220, 255, 235)},
"glowcap": {"A": (140, 120, 200), "B": (200, 195, 220), "C": (200, 160, 255)},
"dewroot": {"A": (150, 210, 110), "B": (170, 130, 80), "C": (220, 255, 190)},
"starbloom": {"A": (255, 170, 220), "B": (110, 150, 90), "C": (255, 230, 120)},
"rod":    {"A": (140, 90, 50), "B": (90, 60, 35), "C": (255, 120, 50)},
"staff":  {"A": (140, 220, 255), "B": (120, 130, 160), "C": (60, 160, 255)},
"armor":  {"A": (160, 170, 195), "B": (110, 120, 145), "C": (255, 210, 80)},
"boots":  {"A": (160, 110, 60), "B": (110, 75, 45), "C": (255, 210, 80)},
"heart":  {"A": (235, 60, 80), "B": (180, 40, 60), "C": (255, 130, 150)},
"ghost":  {"A": (190, 215, 255), "B": (140, 170, 220), "C": (120, 150, 210)},
"npc":    {"A": (230, 190, 150), "B": (90, 110, 70), "C": (255, 200, 90)},
"beacon": {"A": (150, 150, 170), "B": (110, 110, 130), "C": (255, 200, 90)},
"lever":  {"A": (170, 120, 70), "B": (120, 125, 140), "C": (200, 200, 210)},
"pool":   {"A": (90, 180, 235), "B": (60, 130, 190), "C": (160, 230, 255)},
"shrine": {"A": (170, 175, 190), "B": (110, 115, 135), "C": (255, 200, 90)},
"ghoul":  {"A": (70, 60, 110), "B": (50, 40, 80), "C": (160, 255, 160)},
"bat":    {"A": (90, 50, 120), "B": (60, 30, 90), "C": (255, 90, 60)},
"wolf":   {"A": (105, 110, 125), "B": (80, 85, 100), "C": (255, 220, 80)},
"scare_ghoul": {"A": (60, 50, 100), "B": (40, 30, 70), "C": (160, 255, 160)},
"scare_bat":   {"A": (80, 40, 110), "B": (50, 25, 80), "C": (255, 70, 50)},
"scare_wolf":  {"A": (95, 100, 118), "B": (70, 75, 92), "C": (255, 60, 40)},
}

THEME_OUTLINE = {"fantasy": (12, 10, 16), "anime": (58, 38, 92), "western": (54, 36, 22)}

def theme_color(rgb, theme):
    r, g, b = [v / 255.0 for v in rgb]
    h, s, v = colorsys.rgb_to_hsv(r, g, b)
    if theme == "anime":      # bright pastel: lift value, soften sat, mix white
        v = min(1.0, v * 1.15 + 0.10); s = s * 0.75
        r, g, b = colorsys.hsv_to_rgb(h, s, v)
        r, g, b = r * 0.82 + 0.18, g * 0.82 + 0.18, b * 0.82 + 0.18
    elif theme == "western":  # sepia-leaning, desaturated, warm
        s = s * 0.45; v = v * 0.92
        r, g, b = colorsys.hsv_to_rgb(h, s, v)
        r, g, b = r * 0.78 + 0.20, g * 0.78 + 0.14, b * 0.78 + 0.06
    return (int(r * 255), int(g * 255), int(b * 255), 255)

def render(name, grid, theme):
    rows = [ln for ln in grid.strip("\n").split("\n")]
    w = max(len(r) for r in rows); h = len(rows)
    rows = [r.ljust(w, ".") for r in rows]
    base = BASE[name]
    pal = {
        "O": THEME_OUTLINE[theme],
        "A": theme_color(base["A"], theme),
        "B": theme_color(base["B"], theme),
        "C": theme_color(base["C"], theme),
        "W": (255, 255, 255, 255) if theme != "western" else (245, 235, 210, 255),
        "S": tuple(int(c * 0.45) for c in theme_color(base["B"], theme)[:3]) + (255,),
        "G": (255, 220, 120, 255) if theme != "anime" else (255, 200, 235, 255),
    }
    img = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    px = img.load()
    for y, row in enumerate(rows):
        for x, ch in enumerate(row):
            if ch != ".":
                px[x, y] = pal[ch]
    return img

themes = ["fantasy", "anime", "western"]
count = 0
for theme in themes:
    d = os.path.join(OUT, theme)
    os.makedirs(d, exist_ok=True)
    for name, grid in {**SPRITES, **SCARES}.items():
        render(name, grid, theme).save(os.path.join(d, f"{name}.png"))
        count += 1

# Launcher icon: gem on dark rounded square
for size, folder in [(48, "mipmap-mdpi"), (72, "mipmap-hdpi"), (96, "mipmap-xhdpi"), (144, "mipmap-xxhdpi"), (192, "mipmap-xxxhdpi")]:
    icon = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    drw = ImageDraw.Draw(icon)
    drw.rounded_rectangle([0, 0, size - 1, size - 1], radius=size // 6, fill=(24, 18, 44, 255))
    gem = render("gem", SPRITES["gem"], "fantasy").resize((size * 3 // 4, size * 3 // 4), Image.NEAREST)
    icon.alpha_composite(gem, (size // 8, size // 8))
    dd = os.path.join(RES, folder)
    os.makedirs(dd, exist_ok=True)
    icon.save(os.path.join(dd, "ic_launcher.png"))
    count += 1

print(f"wrote {count} images")
